language: java
sudo: false

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
  - openjdk7
  - openjdk6

before_install:
  - echo "MAVEN_OPTS='-Dlicense.skip=true'" > ~/.mavenrc

install:
  # Compile sources with Java 1.8
  - jdk_switcher use oraclejdk8
  - chmod -R 777 ./travis/install.sh
  - ./travis/install.sh
  # Switch back to the original JDK to run the tests
  - jdk_switcher use ${TRAVIS_JDK_VERSION}

script: ./mvnw test -Dmaven.surefire.excludeGroups= -B

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
    - secure: "jWLfOryabB89R5v7nD3V/8ke6+B26UW8E5wjwKj7dDhjfmGUg+KbOShqWrq4\nEAnyE4GltwDLxKErZ5aAPWcT47C3GJYocKtmTcec2sblqMdVVUd3udylrM1d\n66Yb0XZoqri9JJ9pb8ObDp5XRV+ZQ5xP0w1gboNY6SynJg/1FKk="
    - secure: "UV14rAITDqou5jObPInlIS3IYdf45LihGal9/+C4TLyhXLaVktbT/arFAAIF\ndpv9OM+YgeA7ZeRZLJ8vbgipO+rxizPNL1DqK1rp9s5B2F2y9+ir47nTwayL\n0RN7TgdswjzZZKOukWF2CVK1hjk+n8iFkCrorU22trmXlHc0aoE="
