language: java

jdk:
  - openjdk-ea
  - openjdk13
  - openjdk12
  - openjdk11
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo "MAVEN_OPTS='-Dlicense.skip=true'" > ~/.mavenrc

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
    - secure: "jWLfOryabB89R5v7nD3V/8ke6+B26UW8E5wjwKj7dDhjfmGUg+KbOShqWrq4\nEAnyE4GltwDLxKErZ5aAPWcT47C3GJYocKtmTcec2sblqMdVVUd3udylrM1d\n66Yb0XZoqri9JJ9pb8ObDp5XRV+ZQ5xP0w1gboNY6SynJg/1FKk="
    - secure: "UV14rAITDqou5jObPInlIS3IYdf45LihGal9/+C4TLyhXLaVktbT/arFAAIF\ndpv9OM+YgeA7ZeRZLJ8vbgipO+rxizPNL1DqK1rp9s5B2F2y9+ir47nTwayL\n0RN7TgdswjzZZKOukWF2CVK1hjk+n8iFkCrorU22trmXlHc0aoE="
